name: XpUltimate
version: ${version}
description: Advanced XP storage system with bottles and bank with interest
author: NoibeCoded

main: me.noibecoded.xpultimate.XpUltimate

api-version: 1.19

softdepend:
  - Vault
  - PlaceholderAPI

commands:
  xpbottles:
    description: XP Bottle commands
    usage: /xpbottles [create|gui|help]
    permission: xpbottles.use
    permission-message: You don't have permission to use XP Bottle commands.
  xpbank:
    description: XP Bank commands
    usage: /xpbank [deposit|withdraw|transfer|balance|interest|reset|help]
    permission: xpbank.use
    permission-message: You don't have permission to use XP Bank commands.
  xpultimate:
    description: Main XpUltimate commands
    usage: /xpultimate [resourcepack|status|reload|help]
    permission: xpultimate.use
    permission-message: You don't have permission to use XpUltimate commands.

permissions:
  xpbottles.*:
    description: All XP Bottle permissions
    children:
      xpbottles.use: true
      xpbottles.create: true
      xpbottles.gui: true
  xpbottles.use:
    description: Use XP bottle commands
    default: true
  xpbottles.create:
    description: Create XP bottles
    default: true
  xpbottles.gui:
    description: Open XP bottle crafting GUI
    default: true

  xpbank.*:
    description: All XP Bank permissions
    children:
      xpbank.use: true
      xpbank.deposit: true
      xpbank.withdraw: true
      xpbank.transfer: true
      xpbank.balance: true
      xpbank.interest: true
      xpbank.reset: true
      xpbank.reset.others: true
  xpbank.use:
    description: Use XP bank commands
    default: true
  xpbank.deposit:
    description: Deposit XP to bank
    default: true
  xpbank.withdraw:
    description: Withdraw XP from bank
    default: true
  xpbank.transfer:
    description: Transfer XP to other players
    default: true
  xpbank.balance:
    description: Check XP balance
    default: true
  xpbank.interest:
    description: View interest rates
    default: true
  xpbank.reset:
    description: Reset own XP bank
    default: op
  xpbank.reset.others:
    description: Reset other players' XP bank
    default: op

  xpultimate.*:
    description: All XpUltimate permissions
    children:
      xpultimate.use: true
      xpultimate.reload: true
  xpultimate.use:
    description: Use XpUltimate main commands
    default: true
  xpultimate.reload:
    description: Reload plugin configuration
    default: op
